version: '3.8'

services:
  redis: # See Also: https://hub.docker.com/_/redis
    image: redis:7.0.5-alpine
    hostname: hostname-redis
    ports:
      - 6379:6379
  
  mysql: # See Also: https://hub.docker.com/_/mysql
    image: mysql:8.0.31
    hostname: hostname-mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306

  app:
    build: .
    image: python-project
    volumes:
      - .:/app
    depends_on:
      - redis
      - mysql
    ports:
      - 8080:8080
    command: |
      sh -c "./wait-for-it.sh mysql:3306 --
             ./wait-for-it.sh redis:6379 --
             uvicorn src.main:app --reload --host 0.0.0.0 --port 8080"


